# Site settings
title: DevOps 
email: info@quadralogics.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

#Heading 
Head1: DevOps Master Architect Workshop
Head2: Learn from the comfort of your home 
Head3: 72+ hours of the instructor-led, live , hands-on workshop
HeadCTA: Enroll Now
HeadCTALink:

#Call to action
USPH: QuadraLogics Advnatage
USP: Quadralogics is a boutique training firm that specializes in DevOps training and consulting. Since inception in 2014, QuadraLogics has facilitated more than 70+ corporate and public workshops enabling more than 2000+ Practitioners. We are trusted partners with global brands like Pluralsight, Udacity, KnowledgeHut, etc and enable them in designing/delivering technical content and training. Quadralogics today is one of the most trusted training/content producers and a premium player in the B2B DevOps market.Hence enrolling your self with our DevOps Master program entitles you to avail the program at a wholesale price. Building on our experience and exposure our industry experts have carefully handcrafted the “DevOps Master Workshop ” series, we use a technique called the “Task-based learning”. In this approach, the practitioner learns by exploring 200+ hands on,real-life scenarios in our labs. This unique style enables the practitioner to be more competent and highly productive after the workshop. 

#services
ServicesHeading: Key Features

Services1H: 72+ hours of learning
Services1: 72+ hours of the instructor-led, live online hands-on workshop. In-depth coverage of Basic to Advanced topics, ideal for beginners and experienced.

Services2H: 1X1 Coaching
Services2: We understand that learning is never complete without tailoring to your needs. Hence this program includes 1X1 personalized coaching for 3hrs per person.

Services3H: 11 Certification
Services3: This detail master workshop includes 11 certifications across Docker, Kubernetes, Jenkins, Puppet, Ansible, Chef, Terraform, AWS Cloud formation, Nagios, Git, & InSpec.

Services4H: Class recording
Services4: Unable to make it to a class, we have covered you, we will upload the class recording to our LMS website and you will have exclusive access to it for the next 6 months.


#Clinets
clinetsH : Sample Cetificates

#Ribbon 
RHead1: Buy your tickets
RHead2: 
RHead3: 4.July2020Workshop Timings- Sat & Sunday 8 pm to 11 pm IST | Doubt Clearances Session Mon 8 pm to 11 pm IST
RCTA:  Enroll Now!

ph_number: +91-6362315334
github_username: linkedin/company/quadralogics

footer: ©  2020  www.quadralogics.com

# Build settings
markdown: kramdown
